# required packages : nvidia nvidia-utils nvidia-container-toolkit

services:
  init-folders:
    image: alpine
    container_name: init-folders
    user: 1000:1000
    command: >
      sh -c "mkdir -p /media/{disk-base,disk1,disk2}/{anime,cartoons,movies,tv}"
    volumes:
      - ./media:/media
    restart: "no"

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    runtime: nvidia
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - ./media/disk-base:/media/disk-base:rw
      - /mnt/media1:/media/disk1
      - /mnt/media2:/media/disk2
    networks:
      - media-network
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - JELLYFIN_PublishedServerUrl=http://jellyfin.praion.com
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sS http://localhost:8096/ >/dev/null 2>&1 || exit 1",
        ]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 20s

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8080
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - qbittorrent-config:/config
      - ./downloads:/downloads
    restart: unless-stopped
    networks:
      - media-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sS http://localhost:8080/ >/dev/null 2>&1 || exit 1",
        ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 20s

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 9696:9696
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped
    networks:
      - media-network
    dns:
      - 8.8.8.8 # Google DNS
    depends_on:
      qbittorrent:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sS http://localhost:9696/ >/dev/null 2>&1 || exit 1",
        ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 20s

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - sonarr-config:/config
      - ./media/disk-base:/media/disk-base
      - ./downloads:/downloads
      - /mnt/media1:/media/disk1
      - /mnt/media2:/media/disk2
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - media-network
    depends_on:
      qbittorrent:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sS http://localhost:8989/ >/dev/null 2>&1 || exit 1",
        ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 20s

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - radarr-config:/config
      - ./media/disk-base:/media/disk-base
      - /mnt/media1:/media/disk1
      - /mnt/media2:/media/disk2
      - ./downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media-network
    depends_on:
      qbittorrent:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -sS http://localhost:7878/ >/dev/null 2>&1 || exit 1",
        ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 20s

  encoder-base: # base service for encoders
    image: ghcr.io/linuxserver/ffmpeg
    runtime: runc # use runc runtime to run without GPU support
    user: 1000:1000
    volumes:
      - ./media/disk-base/:/media/disk-base
      - /mnt/media1:/media/disk1
      - /mnt/media2:/media/disk2
      - ./scripts:/scripts:ro
    working_dir: /scripts
    cpuset: ${THREAD_PARK:-0-3} # 4 first threads by default
    restart: "no"

  encoder-anime-base:
    extends:
      service: encoder-base

  encoder-anime-disk-base:
    extends:
      service: encoder-anime-base
    container_name: encoder-anime-disk-base
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=anime", "/media/disk-base/anime"]

  encoder-anime-disk1:
    extends:
      service: encoder-anime-base
    container_name: encoder-anime-disk1
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=anime", "/media/disk1/anime"]

  encoder-anime-disk2:
    extends:
      service: encoder-anime-base
    container_name: encoder-anime-disk2
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=anime", "/media/disk2/anime"]

  encoder-movie-base:
    extends:
      service: encoder-base

  encoder-movie-disk-base:
    extends:
      service: encoder-movie-base
    container_name: encoder-movie-disk-base
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=movie", "/media/disk-base/movies"]

  encoder-movie-disk1:
    extends:
      service: encoder-movie-base
    container_name: encoder-movie-disk1
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=movie", "/media/disk1/movies"]

  encoder-movie-disk2:
    extends:
      service: encoder-movie-base
    container_name: encoder-movie-disk2
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=movie", "/media/disk2/movies"]

  encoder-tv-base:
    extends:
      service: encoder-base

  encoder-tv-disk-base:
    extends:
      service: encoder-tv-base
    container_name: encoder-tv-disk-base
    entrypoint: ["/scripts/auto-encode.sh", "--media=tv", "/media/disk-base/tv"]

  encoder-tv-disk1:
    extends:
      service: encoder-tv-base
    container_name: encoder-tv-disk1
    entrypoint: ["/scripts/auto-encode.sh", "--media=tv", "/media/disk1/tv"]

  encoder-tv-disk2:
    extends:
      service: encoder-tv-base
    container_name: encoder-tv-disk2
    entrypoint: ["/scripts/auto-encode.sh", "--media=tv", "/media/disk2/tv"]

  encoder-cartoon-base:
    extends:
      service: encoder-base

  encoder-cartoon-disk-base:
    extends:
      service: encoder-cartoon-base
    container_name: encoder-cartoon-disk-base
    entrypoint:
      [
        "/scripts/auto-encode.sh",
        "--media=cartoon",
        "/media/disk-base/cartoons",
      ]

  encoder-cartoon-disk1:
    extends:
      service: encoder-cartoon-base
    container_name: encoder-cartoon-disk1
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=cartoon", "/media/disk1/cartoons"]

  encoder-cartoon-disk2:
    extends:
      service: encoder-cartoon-base
    container_name: encoder-cartoon-disk2
    entrypoint:
      ["/scripts/auto-encode.sh", "--media=cartoon", "/media/disk2/cartoons"]

volumes:
  jellyfin-config:
  jellyfin-cache:
  qbittorrent-config:
  prowlarr-config:
  sonarr-config:
  radarr-config:

networks:
  media-network:
    driver: bridge
